version: '3'
services:
  confluence:
    image: confluence/confluence:7.4.14
    container_name: 'confluence'
    restart: always
    environment: 
      TZ: Asia/Shanghai
      JVM_MINIMUM_MEMORY: 1024m
      JVM_MAXIMUM_MEMORY: 4096m
    volumes:
    - ./data/confluence/data:/var/atlassian/application-data/confluence
    ports: 
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    restart: always
    environment: 
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: confluence
    volumes:
    - ./data/mysql/data:/var/lib/mysql
    - ./my-confluence.cnf:/etc/mysql/conf.d/my-confluence.cnf
