version: '3.8'
services:
  registry:
    image: registry:2
    container_name: "registry"
    restart: always
    environment: 
      TZ: Asia/Shanghai
    ports:
      - 443:443
      - 5000:5000
    volumes:
      - /data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
      - /ssl/domain.crt:/etc/docker/registry/ssl/domain.crt
      - /ssl/domain.key:/etc/docker/registry/ssl/domain.key
