version: '3.8'
services:
  registry:
    image: registry:2
    container_name: "registry"
    restart: always
    environment: 
      TZ: Asia/Shanghai
    ports:
      - 443:443
    volumes:
      - /data/registry:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
      - /ssl:/etc/docker/registry/ssl