version: '3.8'
services:
  gitlab-runner:
    image: gitlab-runner-centos:latest
    container_name: "runner"
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/etc/gitlab-runner
  gitlab-runner2:
    image: gitlab-runner-centos:latest
    container_name: "runner2"
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/etc/gitlab-runner
  gitlab-runner3:
    image: gitlab-runner-centos:latest
    container_name: "runner3"
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/etc/gitlab-runner
  gitlab-runner4:
    image: gitlab-runner-centos:latest
    container_name: "runner4"
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/etc/gitlab-runner
