version: '3.8'
services:
  gitlab-runner:
    image: gitlab-runner-centos:latest
    container_name: "runner"
    restart: always
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/etc/gitlab-runner
    privileged: true
    command: ["/usr/sbin/init"]
  gitlab-runner2:
    image: gitlab-runner-centos:latest
    container_name: "runner2"
    restart: always
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/etc/gitlab-runner
    privileged: true
    command: ["/usr/sbin/init"]
  gitlab-runner3:
    image: gitlab-runner-centos:latest
    container_name: "runner3"
    restart: always
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/etc/gitlab-runner
    privileged: true
    command: ["/usr/sbin/init"]
  gitlab-runner4:
    image: gitlab-runner-centos:latest
    container_name: "runner4"
    restart: always
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/etc/gitlab-runner
    privileged: true
    command: ["/usr/sbin/init"]
