version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    restart: always
    environment: 
      TZ: Asia/Shanghai
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana
