version: '3.8'
services:
  mysql:
    image: iredmail/mariadb:stable
    container_name: 'iredmail'
    restart: always
    hostname: mail
    domainname: example.io
    environment: 
      TZ: Asia/Shanghai
    volumes:
      - ./iredmail/data/backup:/var/vmail/backup
      - ./iredmail/data/mailboxes:/var/vmail/vmail1
      - ./iredmail/data/mlmmj:/var/vmail/mlmmj
      - ./iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive
      - ./iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy
      - ./iredmail/data/custom:/opt/iredmail/custom
      - ./iredmail/data/ssl:/opt/iredmail/ssl
      - ./iredmail/data/mysql:/var/lib/mysql
      - ./iredmail/data/clamav:/var/lib/clamav
      - ./iredmail/data/sa_rules:/var/lib/spamassassin
      - ./iredmail/data/postfix_queue:/var/spool/postfix
    ports: 
      - "80:80"
      - "443:443"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "25:25"
      - "465:465"
      - "587:587"
      