version: '3.8'
services:
  mysql:
    image: mysql:5.7.31
    container_name: 'mysql'
    restart: always
    environment: 
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
    - ./mysqldata:/var/lib/mysql
    ports: 
      - "3306:3306"
