version: '3.8'
services:
  zentao:
    image: easysoft/zentao:12.4.stable
    container_name: 'zentao'
    hostname: 'zentao.example.io'
    restart: always
    environment: 
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
    - ./www/zentaopms:/www/zentaopms
    - ./www/mysqldata:/var/lib/mysql
    ports: 
      - "80:80"
