version: '3.8'
services:
  redis:
    image: redis:5
    container_name: 'redis'
    restart: always
    environment: 
      TZ: Asia/Shanghai
    volumes:
    - ./data:/data
    ports: 
      - "6379:6379"
